// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ComboSelectController from "./combo_select_controller"
application.register("combo-select", ComboSelectController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilePickerController from "./file_picker_controller"
application.register("file-picker", FilePickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import ProductFormController from "./product_form_controller"
application.register("product-form", ProductFormController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import UploadedFileController from "./uploaded_file_controller"
application.register("uploaded-file", UploadedFileController)
